### ISSUE TITLE
Not all Device Pages visible - Failed to execute 'atob' on 'Window'

### ISSUE THREAD

**Issue by roe1974** [jokob-sk/NetAlertX#1132]
### Is there an existing issue for this?

- [x] I have searched the existing open and closed issues and I checked the docs https://jokob-sk.github.io/NetAlertX/

### The issue occurs in the following browsers. Select at least 2.

- [ ] Firefox
- [x] Chrome
- [ ] Edge
- [ ] Safari (unsupported) - PRs welcome
- [ ] N/A - This is an issue with the backend

### Current Behavior

With the latest version, all my devices have disappeared from the list ? It says ‘processing...’ in the middle, but nothing is displayed?

### Expected Behavior

Devices are in the List

### app.conf

```python

```

### docker-compose.yml

```python

```

### What installation are you running?

Production (netalertx)

### Debug enabled

- [x] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by roe1974** [comment]
OK .. problem persists ... i see the first page of my devices.... switching to 2nd page shows "processing...." now till 10 minutes ...

**Comment by jokob-sk** [comment]
Hi there,

In order to help, please provide:

1. Screenshot of the issue
2. Logs from Maintenance when the issue occurs
3. Browser console log
4. The version you are using

Thanks, j

**Comment by roe1974** [comment]
PS: changed the viewable amount of devices to 50 ... now is see only: loading.....

Version: 25.8.6
log is full of:

`13:31:14 [HELPER] ⚠ ERROR not processed set_type:  {"dataType":"array","elements":[{"elementType":"select","elementOptions":[{"multiple":"true","ordeable":"true"}],"transformers":[]},{"elementType":"button","elementOptions":[{"sourceSuffixes":[]},{"separator":""},{"cssClasses":"col-xs-12"},{"onClick":"selectChange(this)"},{"getStringKey":"Gen_Change"}],"transformers":[]}]} 
13:31:14 [HELPER] ⚠ ERROR not processed set_value: ['ARPSCAN', 'CSVBCKP', 'DBCLNP', 'INTRNT', 'MAINT', 'NEWDEV', 'NSLOOKUP', 'NTFPRCS', 'AVAHISCAN', 'SETPWD', 'SMTP', 'SYNC', 'VNDRPDT', 'WORKFLOWS', 'UI', 'CUSTPROP', 'TELEGRAM'] 
13:31:14 [Plugins] Processed and deleted file: /app/log/plugins/last_result.NBTSCAN.log 
13:31:14 [Plugins] No output received from the plugin "NBTSCAN"
13:31:14 [Plugin utils] ---------------------------------------------
13:31:14 [Plugin utils] display_name: NSLOOKUP (Name discovery)
13:31:14 [Plugins] Executing: python3 /app/front/plugins/nslookup_scan/nslookup.py
13:31:14 [Plugins] Output: [plugin_helper] reading config file
13:31:14 [NSLOOKUP] In script
13:31:14 [Database] Opening DB
13:31:14 [NSLOOKUP] Devices count: 0
13:31:14 [NSLOOKUP] Script finished`

<img width="1523" height="766" alt="Image" src="https://github.com/user-attachments/assets/2cc5a15c-b2f4-4c0d-82f3-3450b6b29599" />

**Comment by roe1974** [comment]
after container restart:

<img width="453" height="199" alt="Image" src="https://github.com/user-attachments/assets/15b80321-1b4b-4ea7-993d-4fd3588f7151" />

**Comment by roe1974** [comment]
PS: 
Views with few devices (e.g. network devices, which contain 4 devices) are displayed immediately ...

**Comment by roe1974** [comment]
Chrome Console Log:

`Error while trying to use the following icon from the Manifest: http://192.168.0.144:20211/img/manifest.json (Download error or resource isn't a valid image)`

`ui_components.js?v=v25.8.6:816 Uncaught InvalidCharacterError: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
    at renderDeviceLink (ui_components.js?v=v25.8.6:816:37)
    at k.fn.init.createdCell (devices.php:1675:28)
    at Ha (jquery.dataTables.min.js:25:167)
    at O (jquery.dataTables.min.js:16:421)
    at wb (jquery.dataTables.min.js:40:32)
    at jquery.dataTables.min.js:37:167
    at i (jquery.dataTables.min.js:35:338)
    at Object.success (jquery.dataTables.min.js:36:40)
    at c (jquery.min.js:2:27742)
    at Object.fireWith [as resolveWith] (jquery.min.js:2:28487)`

**Comment by jokob-sk** [comment]
Thank you.

Looks like one of the devices has an incorrectly encoded icon. I'd recommend checking your devices and making sure the Icons are valid and correctly displayed on the device details pages of all devices. You can also reset icons with the multi edit functionality.

Before doing anything I'd recommend taking some backups.

https://jokob-sk.github.io/NetAlertX/BACKUPS/?h=backup#backup-strategies
https://jokob-sk.github.io/NetAlertX/DEVICES_BULK_EDITING/?h=mult

**Comment by jokob-sk** [comment]
>... now till 10 minutes ?!?

>... the list?!?!? 

Also, a word of advice. If you write like this I really don't want to help you. Using things like this `?!?` is disrespectful to people who maintain Foss applications for free. Bugs are normal in any product.

**Comment by roe1974** [comment]
Sorry, I didn't mean to stress you out or attack you with the ‘?!?’ :-) ... I'll refrain from doing that ;-)

All icons deleted, problem remains:
The problem on the device page is that the first page works (20 devices) and the third page (4 devices) ... Page 2 doesn't work (‘processing’)

And the exciting thing is... I didn't change anything on the devices... the error occurred suddenly (I can't say whether it's related to the current version).

I have deleted the container and reloaded it (the whole thing runs on a Synology under DSM 6.2.x) ... I couldn't open the Devices page for about 10-15 minutes, and the error in the Chrome Console appeared on all device pages... Then suddenly the first page works again, and the third, but the second page still doesn't... However, when I go to ‘Network’, I can see my network with all devices (online and offline) and all the icons next to them.

br, Richard
PS: ... and I love your project, great work!!
PSS: As an idea... you could add something to ui_components.js that catches the error when calling atob(), so that the script no longer crashes but handles it in a controlled manner... replacing a defective icon with a ‘?’ for example?

**Comment by roe1974** [comment]
I exported the devices to csv ... there I checked every Base64 icon (https://base64.guru/converter/decode/file) ... all icons are displayed correctly, as there are no errors in the Base64 encoding ... strange.
br Richard

**Comment by jokob-sk** [comment]
Thanks for the details. I don't like implementing try/catch segments as this obfuscates and hides errors. 

I've pushed a new dev version with some additional logging to debug this further.

Can you please switch to the `netalertx-dev` docker image (backup everything at first or, ideally, spin up a **separate container with a separate db and config** as DB modifications can happen), in about 15 minutes (or after the latest [action finishes](https://github.com/jokob-sk/NetAlertX/actions)) from now?

Make sure you refresh your browser cache - and click the 🔄 refresh button in the top right corner.

Please post your browser console log with the following section before the error occurs:

<img width="718" height="833" alt="Image" src="https://github.com/user-attachments/assets/90d981d9-1476-42e7-ad87-3ca1376e7b55" />

**Comment by roe1974** [comment]
Hey, here we go ;-)

<img width="556" height="654" alt="Image" src="https://github.com/user-attachments/assets/409e0298-bf56-4e58-8ca8-d7f4658cf18c" />

i also tried a complete fresh installation and imported the csv backup of my devices, same problem. I use chrome on MAC ... could this be the impact ?

**Comment by roe1974** [comment]
today, i see two new errors on the browser console-log while opnening device page (second error is on each page).

`devices.php:1 Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received`

`Error while trying to use the following icon from the Manifest: http://192.168.0.144:20211/img/manifest.json (Download error or resource isn't a valid image)`

br Richard

**Comment by roe1974** [comment]
there is one device with two presence sessions ... the only one with two ... could that be the problem ?

<img width="616" height="61" alt="Image" src="https://github.com/user-attachments/assets/fb64c9c3-edb7-4dd5-978a-e8449f2bec22" />

**Comment by roe1974** [comment]
found this in the app.log ... can this be the reason ?

`13:03:02 [AVAHISCAN] In script
13:03:02 [Database] Opening DB
13:03:02 [AVAHISCAN] Devices count: 44
13:03:02 [AVAHISCAN] ⚠ ERROR - Failed to create client object: Daemon not running

13:03:02 [AVAHISCAN] Scan: FAIL - check logs
13:03:02 [AVAHISCAN] ⚠ ERROR - Failed to create client object: Daemon not running

13:03:02 [AVAHISCAN] Scan: FAIL - check logs
13:03:02 [AVAHISCAN] ⚠ ERROR - Failed to create client object: Daemon not running

13:03:02 [AVAHISCAN] Scan: FAIL - check logs
13:03:02 [AVAHISCAN] ⚠ ERROR - Failed to create client object: Daemon not running

13:03:02 [AVAHISCAN] Scan: FAIL - check logs
13:03:02 [AVAHISCAN] ⚠ ERROR - Failed to create client object: Daemon not running

13:03:02 [AVAHISCAN] Scan: FAIL - check logs
13:03:02 [AVAHISCAN] ⚠ ERROR - Failed to create client object: Daemon not running

13:03:02 [AVAHISCAN] Scan: FAIL - check logs
13:03:02 [AVAHISCAN] ⚠ ERROR - Failed to create client object: Daemon not running

13:03:02 [AVAHISCAN] Scan: FAIL - check logs
13:03:02 [AVAHISCAN] ⚠ ERROR - Failed to create client object: Daemon not running

13:03:02 [AVAHISCAN] Scan: FAIL - check logs
13:03:02 [AVAHISCAN] ⚠ ERROR - Failed to create client object: Daemon not running

13:03:02 [AVAHISCAN] Scan: FAIL - check logs
13:03:02 [AVAHISCAN] ⚠ ERROR - Failed to create client object: Daemon not running

13:03:02 [AVAHISCAN] Scan: FAIL - check logs
13:03:02 [AVAHISCAN] ⚠ ERROR - Failed to create client object: Daemon not running

13:03:02 [AVAHISCAN] Scan: FAIL - check logs
13:03:02 [AVAHISCAN] ⚠ ERROR - Failed to create client object: Daemon not running

13:03:02 [AVAHISCAN] Scan: FAIL - check logs
13:03:02 [AVAHISCAN] ⚠ ERROR - Failed to create client object: Daemon not running

13:03:02 [AVAHISCAN] Scan: FAIL - check logs
13:03:02 [AVAHISCAN] ⚠ ERROR - Failed to create client object: Daemon not running

13:03:02 [AVAHISCAN] Scan: FAIL - check logs
13:03:02 [AVAHISCAN] ⚠ ERROR - Failed to create client object: Daemon not running

13:03:02 [AVAHISCAN] Scan: FAIL - check logs
13:03:02 [AVAHISCAN] ⚠ ERROR - Failed to create client object: Daemon not running

13:03:02 [AVAHISCAN] Scan: FAIL - check logs
13:03:02 [AVAHISCAN] ⚠ ERROR - Failed to create client object: Daemon not running

13:03:02 [AVAHISCAN] Scan: FAIL - check logs
13:03:02 [AVAHISCAN] ⚠ ERROR - Failed to create client object: Daemon not running

13:03:02 [AVAHISCAN] Scan: FAIL - check logs
13:03:02 [AVAHISCAN] ⚠ ERROR - Failed to create client object: Daemon not running

13:03:02 [AVAHISCAN] Scan: FAIL - check logs
13:03:02 [AVAHISCAN] ⚠ ERROR - Failed to create client object: Daemon not running

13:03:02 [AVAHISCAN] Scan: FAIL - check logs
13:03:02 [AVAHISCAN] ⚠ ERROR - Failed to create client object: Daemon not running

13:03:02 [AVAHISCAN] Scan: FAIL - check logs
13:03:02 [AVAHISCAN] ⚠ ERROR - Failed to create client object: Daemon not running

13:03:02 [AVAHISCAN] Scan: FAIL - check logs
13:03:02 [AVAHISCAN] ⚠ ERROR - Failed to create client object: Daemon not running

13:03:02 [AVAHISCAN] Scan: FAIL - check logs
13:03:02 [AVAHISCAN] ⚠ ERROR - Failed to create client object: Daemon not running

13:03:02 [AVAHISCAN] Scan: FAIL - check logs
13:03:02 [AVAHISCAN] ⚠ ERROR - Failed to create client object: Daemon not running

13:03:02 [AVAHISCAN] Scan: FAIL - check logs
13:03:02 [AVAHISCAN] ⚠ ERROR - Failed to create client object: Daemon not running

13:03:02 [AVAHISCAN] Scan: FAIL - check logs
13:03:02 [AVAHISCAN] ⚠ ERROR - Failed to create client object: Daemon not running

13:03:02 [AVAHISCAN] Scan: FAIL - check logs
13:03:02 [AVAHISCAN] ⚠ ERROR - Failed to create client object: Daemon not running

13:03:02 [AVAHISCAN] Scan: FAIL - check logs
13:03:02 [AVAHISCAN] ⚠ ERROR - Failed to create client object: Daemon not running

13:03:02 [AVAHISCAN] Scan: FAIL - check logs
13:03:02 [AVAHISCAN] ⚠ ERROR - Failed to create client object: Daemon not running

13:03:02 [AVAHISCAN] Scan: FAIL - check logs
13:03:02 [AVAHISCAN] ⚠ ERROR - Failed to create client object: Daemon not running

13:03:02 [AVAHISCAN] Scan: FAIL - check logs
13:03:02 [AVAHISCAN] ⚠ ERROR - Failed to create client object: Daemon not running

13:03:02 [AVAHISCAN] Scan: FAIL - check logs
13:03:02 [AVAHISCAN] ⚠ ERROR - Failed to create client object: Daemon not running

13:03:02 [AVAHISCAN] Scan: FAIL - check logs
13:03:02 [AVAHISCAN] ⚠ ERROR - Failed to create client object: Daemon not running

13:03:02 [AVAHISCAN] Scan: FAIL - check logs
13:03:02 [AVAHISCAN] ⚠ ERROR - Failed to create client object: Daemon not running

13:03:02 [AVAHISCAN] Scan: FAIL - check logs
13:03:02 [AVAHISCAN] ⚠ ERROR - Failed to create client object: Daemon not running

13:03:02 [AVAHISCAN] Scan: FAIL - check logs
13:03:02 [AVAHISCAN] ⚠ ERROR - Failed to create client object: Daemon not running

13:03:02 [AVAHISCAN] Scan: FAIL - check logs
13:03:02 [AVAHISCAN] ⚠ ERROR - Failed to create client object: Daemon not running

13:03:02 [AVAHISCAN] Scan: FAIL - check logs
13:03:02 [AVAHISCAN] ⚠ ERROR - Failed to create client object: Daemon not running

13:03:02 [AVAHISCAN] Scan: FAIL - check logs
13:03:02 [AVAHISCAN] ⚠ ERROR - Failed to create client object: Daemon not running

13:03:02 [AVAHISCAN] Scan: FAIL - check logs
13:03:02 [AVAHISCAN] ⚠ ERROR - Failed to create client object: Daemon not running

13:03:02 [AVAHISCAN] Scan: FAIL - check logs
13:03:02 [AVAHISCAN] ⚠ ERROR - Failed to create client object: Daemon not running

13:03:02 [AVAHISCAN] Scan: FAIL - check logs
13:03:02 [AVAHISCAN] ⚠ ERROR - Failed to create client object: Daemon not running

13:03:02 [AVAHISCAN] Scan: FAIL - check logs
13:03:02 [AVAHISCAN] ⚠ ERROR - Failed to create client object: Daemon not running

13:03:02 [AVAHISCAN] Scan: FAIL - check logs
13:03:02 [AVAHISCAN] Script finished`

**Comment by jokob-sk** [comment]
Thanks for the details.

The base64 encoded string from your screenshot seems to convert fine:

`PGkgY2xhc3M9ImZhIGZhLXdpZmkiPjwvaT4=`

to 

`<i class="fa fa-wifi"></i>`

1. Can you confirm this is the last log entry before the error occurs?


> 13:03:02 [AVAHISCAN] Scan: FAIL - check logs
> 13:03:02 [AVAHISCAN] ⚠ ERROR - Failed to create client object: Daemon not running

You can usually ignore these as it takes a bit for the demon to start up. 

The following error is not related to the current issue I think:

> Error while trying to use the following icon from the Manifest: http://192.168.0.144:20211/img/manifest.json (Download error or resource isn't a valid image)

This error is a bit vague to debug this:

> devices.php:1 Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received


> i also tried a complete fresh installation and imported the csv backup of my devices, same problem. I use chrome on MAC ... could this be the impact ?

Not sure, at first I need to be able to reproduce the error (I don't own a  mac).

If you'd like you can try a different browser or send me the exported devices.csv to netalertx@gmail.com and I can try reproducing it on my end. Feel free to redact sensitive data.

**Comment by roe1974** [comment]
Add 1: Yes, that was the last log before the error.
However, I am unable to verify this at present, as the device view is no longer accessible. After some waiting time and several browser restarts, pages 1 and 3 may be become accessible.
Through Monitoring -> e.g. presence, I am able to access all devices and their details without any issues. Only all views under Devices are causing problems, except for “Network Devices,” which is accessible without any issues.

br Richard :-)

**Comment by jokob-sk** [comment]
If you'd like you can try a different browser or send me the exported devices.csv to netalertx@gmail.com and I can try reproducing it on my end. Feel free to redact sensitive data.

**Comment by roe1974** [comment]
What can I hide in the CSV file so that it still works for you? (MAC, IP, ????) ... What is encoded in the devGUID and devCustomProps columns?

**Comment by jokob-sk** [comment]
Hi @roe1974 ,

Thanks in advance, and for your persistence - sometimes these bugs take a while to find - hope this will help us to get to the resolution of this.

- There are no checks on IP uniqueness,  so IPs can be changed however you want.
- MACs have to be unique, that is the only requirement. 
- You should be able to remove Custom Properties completely (we can re-visit this decision if I can't reproduce the error on the supplied data set) - here is a default value you can use `WwogIFsKICAgIHsKICAgICAgIkNVU1RQUk9QX2ljb24iOiAiUEdrZ1kyeGhjM005SW1aaGN5Qm1ZUzEwY21GemFDMWhiSFFpUGp3dmFUND0iCiAgICB9LAogICAgewogICAgICAiQ1VTVFBST1BfdHlwZSI6ICJkZWxldGVfZGV2IgogICAgfSwKICAgIHsKICAgICAgIkNVU1RQUk9QX25hbWUiOiAiIgogICAgfSwKICAgIHsKICAgICAgIkNVU1RQUk9QX2FyZ3MiOiAiRGVsZXRlIGRldmljZSIKICAgIH0sCiAgICB7CiAgICAgICJDVVNUUFJPUF9ub3RlcyI6ICIiCiAgICB9LAogICAgewogICAgICAiQ1VTVFBST1Bfc2hvdyI6IHRydWUKICAgIH0KICBdCl0=`

An idea is also just to provide the handful of devices that you know causes the issue (e.g. you can try to narrow down the devices by deleting everything down to the corrupted entry (e.g. by [divide an conquer](https://en.wikipedia.org/wiki/Divide-and-conquer_algorithm) - halving and testing the dataset - e.g. via the multi-edit functionality).

Thanks in advance,
j

**Comment by roe1974** [comment]
Heyyyyyy ... i found the error :-)
I had three devices with an invalid “devParentMAC” address (namely, the MAC address of the old router that I replaced a few weeks ago). I corrected the three and the devices view is working normally again. Juhuuuuuuuuuu :-) :-) ... Is this a bug?
One more question: I reset all “devType” values to “none,” but they are automatically filled in again (often incorrectly). Can I disable this somewhere?
br Richard

**Comment by jokob-sk** [comment]
Hey, great, thanks for the update! 

Yes, sounds like a bug - pushed hopefully a change that would fix this behavior in future. 

On the `devType` question: if `devType in ('', 'null')` then type guessing will continue, so if you set it to e.g. "none" (string, not the "X none" option which saves and empty string) or you use another arbitrary value (e.g. "-") then the guessing for teh type and device will stop. 

More info here: https://jokob-sk.github.io/NetAlertX/DEVICE_HEURISTICS/

**Comment by guillochon** [comment]
I updated to `netalertx-dev` and I am still seeing the same behavior on the devices page. Like @roe1974 I also recently replaced my router, however I had successfully executed the previous netalertx update with no issue after I had replaced the router (it was only after updating to the latest version I saw it crop up).

It looks like the latest version makes the parent network node "fancier" looking so I suspect it's because my old router was removed from the device list and it used to be the "parent" of many nodes. The problem is I don't know how to clear the parent from the nodes since I can't view the devices page.

**Comment by guillochon** [comment]
OK, I fixed it manually, I went into the multi-edit and control clicked every device in the drop down and set it to the new router. Now the devices page is showing up just fine.

**Comment by jokob-sk** [comment]
Would be great if you could double-check this statement, because I hope it’s fixed in the dev image, even if an incorrect parent is present.

> I updated to netalertx-dev and I am still seeing the same behavior on the devices page. Like @roe1974 I also recently replaced my router, however I had successfully executed the previous netalertx update with no issue after I had replaced the router (it was only after updating to the latest version I saw it crop up).

**Comment by guillochon** [comment]
Yeah it wasn't working under dev, devices page wasn't loading at all (as in my prior screenshot). Tried two different browsers and shift+refresh. Wasn't until I went into multi-edit that I was able to fix it.

I figured this was the issue because my "new" group of devices displayed, those devices were all added after the router replacement so none of them had the old, deleted router as a parent.

**Comment by jokob-sk** [comment]
Thanks @guillochon - realized there is still an issue in the code. Hopefully now it will be fixed.

**Comment by roe1974** [comment]
Thx @jokob-sk for the great work !
br Richard 👍

**Comment by rikzuc** [comment]
Hi @jokob-sk ,
I am getting some similar errors. First, I tried to clean all the icons, to fix all the parent nodes, I also assigned each device to an owner (the same). It looks like it resolved the infinite "Loading" of the devices page, however, I still have in the log the following error:

10:09:29 [HELPER] ⚠ ERROR not processed set_type:  {"dataType":"array","elements":[{"elementType":"select","elementOptions":[{"multiple":"true","ordeable":"true"}],"transformers":[]},{"elementType":"button","elementOptions":[{"sourceSuffixes":[]},{"separator":""},{"cssClasses":"col-xs-12"},{"onClick":"selectChange(this)"},{"getStringKey":"Gen_Change"}],"transformers":[]}]} 
10:09:29 [HELPER] ⚠ ERROR not processed set_value: ['ARPSCAN', 'PIHOLE', 'INTRNT', 'NSLOOKUP', 'DIGSCAN', 'SMTP', 'CSVBCKP', 'CUSTPROP', 'DBCLNP', 'MAINT', 'NEWDEV', 'NTFPRCS', 'SETPWD', 'SYNC', 'UI', 'VNDRPDT', 'WORKFLOWS'] 

Moreover, I noticed that after running the ARP scan, two things happen:
- first, in the log I see the following error: 
10:10:45 [setting_value_to_python_type] Error decoding JSON object: Expecting value: line 1 column 1 (char 0)
- second, the status bar is the following:

<img width="350" height="52" alt="Image" src="https://github.com/user-attachments/assets/d7e67402-4284-4b0f-95c8-fb6ba19c648f" />

I see "Check scan" instead of the usual "Process: idle". Beside this, the ARP scan is supposed to run every five minutes, but after the first run it is not scheduled anymore, this is the log:
10:10:45 [Process Scan] Stats end
10:10:45 [Process Scan] Sessions Events (connect / disconnect)
10:10:45 [Process Scan] Creating new devices
10:10:45 [setting_value_to_python_type] Error decoding JSON object: Expecting value: line 1 column 1 (char 0)
10:10:45 default
10:10:46 [Process Scan] Updating Devices Info
10:10:46 [Process Scan] Pairing session events (connection / disconnection) 
10:10:46 [Process Scan] Creating sessions snapshot
10:10:46 [Process Scan] Inserting scan results into Online_History
10:16:32 [graphql_server] data: .... //THIS IS WHERE I CHANGED PAGE

Also, running it manually doesn't do anything, it doesn't write anything on the logs as well. I don't know if the "Check scan" is an indicator of an issue.

I have tried using both the stable and the dev image, because with the stable one I was not able to open the Network page due to a javascript error ("Cannot read type of undefined...") while with the dev image it works fine; the things described above are happening with both images.
Thank you!

**Comment by jokob-sk** [comment]
Hi @rikzuc ,

Please open a separate issue as this specific one is solved in the dev image as reported by the original poster.

Thanks,
J

**Comment by jokob-sk** [comment]
releasing -> closing
