### ISSUE TITLE
date column for events only shows "b-"

### ISSUE THREAD

**Issue by timhae** [jokob-sk/NetAlertX#1147]
### Is there an existing issue for this?

- [x] I have searched the existing open and closed issues and I checked the docs https://jokob-sk.github.io/NetAlertX/

### The issue occurs in the following browsers. Select at least 2.

- [x] Firefox
- [x] Chrome
- [ ] Edge
- [ ] Safari (unsupported) - PRs welcome
- [ ] N/A - This is an issue with the backend

### Current Behavior

Thanks for the great tool, I noticed one issue:

<img width="3498" height="1917" alt="Image" src="https://github.com/user-attachments/assets/7f1d287c-c589-4b14-af1a-f4013bfa85b0" />

### Expected Behavior

the date column shows a date. I looked into the db, there it is formated like a valid date: `6a:93:6f:f7:9b:ac|10.0.0.28|2025-08-23 14:56:18+02:00|Connected||0|` (different device..)

### Steps To Reproduce

1. go to the events tab for any device
2. see event dates as "b-"

### app.conf

```python
file was too large for the issue so I uploaded it to my server, see here: https://haering.dev/app.conf
```

### docker-compose.yml

```python
exec podman  \
  run \
  --name=netalertx \
  --log-driver=journald \
  --cidfile=/run/netalertx/ctr-id \
  --cgroups=enabled \
  --sdnotify=conmon \
  -d \
  --replace \
  -e APP_CONF_OVERRIDE='{"SCAN_SUBNETS":"['\''10.0.0.0/24 --interface=eth0'\'']","UI_theme":"System","LOG_LEVEL":"trace","REPORT_DASHBOARD_URL":"https://netalertx.pi.lan"}' \
  -e LISTEN_ADDR=127.0.0.1 \
  -e LOADED_PLUGINS='["ARPSCAN","AVAHISCAN","CUSTPROP","DBCLNP","DDNS","DHCPLSS","DHCPSRVS","DIGSCAN","ICMP","INTRNT","INTRSPD","IPNEIGH","MAINT","NBTSCAN","NMAP","NMAPDEV","NSLOOKUP","NTFPRCS","NTFY","SNMPDSC","UI","VNDRPDT","WEBMON","WOL"]' \
  -e PGID=300 \
  -e PORT=20211 \
  -e PUID=200 \
  -e TZ=Europe/Berlin \
  -v /var/lib/netalertx/config:/app/config \
  -v /var/lib/netalertx/db:/app/db \
  -v /var/lib/netalertx/log:/app/log \
  --rm \
  --cap-add=NET_RAW \
  --pull missing \
  '--network=host' \
  '--tmpfs=/app/api' \
  ghcr.io/jokob-sk/netalertx:latest
```

### What installation are you running?

Production (netalertx)

### app.log

[log.txt](https://github.com/user-attachments/files/21949495/log.txt)

### Debug enabled

- [x] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
Hi @timhae ,

Thanks for the detailed report, this helps a lot!

I've tested the date you posted above, and it seems to be resolved correctly. 

```javascript
                test = '2025-08-23 14:56:18+02:00'
                console.log(localizeTimestamp(test));
```

console output:

<img width="601" height="33" alt="Image" src="https://github.com/user-attachments/assets/3f2a3b7e-2af0-4f0c-8179-e8f600a9b13e" />

However, that might be coming from a different column, so to make sure, can you try running the following code in your browser console whilst yo have that page open?

```javascript
  
   mac = getMac()

  rawSql = `
    SELECT eve_DateTime, eve_DateTime, eve_EventType, eve_IP, eve_AdditionalInfo
    FROM Events 
    WHERE eve_MAC = "${mac}" 
      AND (
        (eve_EventType NOT IN ("Connected", "Disconnected", "VOIDED - Connected", "VOIDED - Disconnected"))
      )
  `;

  apiUrl = `php/server/dbHelper.php?action=read&rawSql=${btoa(encodeURIComponent(rawSql))}`;

  $.get(apiUrl, function (data) { console.log(JSON.parse(data)) })

```

Please post the result, which should be looking like this:

<img width="577" height="354" alt="Image" src="https://github.com/user-attachments/assets/d3c10499-deb9-4999-bb17-8c94755976ff" />

This will hopefully show us what's stored in the Date column and I can test the `localizeTimestamp` method on those values.

**Comment by timhae** [comment]
Hey, thanks for getting back to me so quickly, the returned data looks similar in my browser:
```
[
  ...more of the same
  {
    "eve_DateTime": "2025-08-24 13:00:53+02:00",
    "eve_EventType": "IP Changed",
    "eve_IP": "10.0.0.24",
    "eve_AdditionalInfo": "Previous IP: 10.0.0.21"
  },
  {
    "eve_DateTime": "2025-08-24 13:06:05+02:00",
    "eve_EventType": "IP Changed",
    "eve_IP": "10.0.0.21",
    "eve_AdditionalInfo": "Previous IP: 10.0.0.24"
  }
]
```

**Comment by jokob-sk** [comment]
I think I've found the issue. This should be fixed in the next release. It would be great if you could test this. Can you please switch to the `netalertx-dev` docker image (backup everything at first or, ideally, spin up a **separate container with a separate db and config** as DB modifications can happen), in about 15 minutes (or after the latest [action finishes](https://github.com/jokob-sk/NetAlertX/actions)) from now?

Make sure you refresh your browser cache - and click the 🔄 refresh button in the top right corner.

Thanks in advance,
j

**Comment by timhae** [comment]
Hey, I also tried on the latest dev and it still shows "b-"

<img width="1894" height="903" alt="Image" src="https://github.com/user-attachments/assets/7ec3e7e9-6604-4529-a7c0-7881c595d60b" />

**Comment by jokob-sk** [comment]
Hi @timhae ,

Tried something different, can you re-test in 15 min?

**Comment by timhae** [comment]
yep, that fixes it (running on `Built on: 2025-08-29 | Version: 17:39:42 - Dev`). Thanks for your time and help!

**Comment by jokob-sk** [comment]
Thanks for checking @timhae - the fix will be included in the next release.

**Comment by jokob-sk** [comment]
releasing -> closing
