### ISSUE TITLE
Error "pcap_activate: eth0: You don't have permission to perform this capture on that device (socket: Operation not permitted)"

### ISSUE THREAD

**Issue by mixio60** [jokob-sk/NetAlertX#1376]
### What installation are you running?

Production (netalertx) 📦

### Did I research?

- [x] I have searched the docs https://jokob-sk.github.io/NetAlertX/
- [x] I have searched the existing open and closed issues
- [x] I confirm my SCAN_SUBNETS is configured and tested as per https://github.com/jokob-sk/NetAlertX/blob/main/docs/SUBNETS.md

### The issue occurs in the following browsers. Select at least 2.

- [ ] Firefox
- [x] Chrome
- [ ] Other (unsupported) - PRs welcome
- [ ] N/A - This is an issue with the backend

### What I want to do

I installed NetAlertX with Portainer on my Synology NAS.
It installed without any problems. I added my subnet with the correct interface settings (192.168.178.0/24 - -interface=eth0, the subnet also used in older netalertX configurations), but the system doesn't detect any devices except the Synology and my Internet access.
When I try an arp-scan on the console, I get an error:
"pcap_activate: eth0: You do not have permission to perform this scan on that device. (socket: Operation prohibited)"

### docker-compose.yml

```python
services:
  netalertx:
     image: ghcr.io/jokob-sk/netalertx-dev:latest
     container_name: NetAlertX
     healthcheck:
      test: curl -f http://localhost:20211/ || exit 1
     mem_limit: 4g
     cpu_shares: 768
     network_mode: host
     read_only: true
     security_opt:
      - no-new-privileges:true
     cap_drop:
      - ALL                  
     cap_add:
      - NET_RAW
      - NET_ADMIN
      - NET_BIND_SERVICE
     volumes:
      - /volume1/docker/netalertx/data:/data:rw
      - /etc/localtime:/etc/localtime:ro
     tmpfs:
      - "/tmp:uid=20211,gid=20211,mode=1700,rw,noexec,nosuid,nodev,async,noatime,nodiratime"
     environment:
      PORT: 20211
     restart: on-failure:5
```

### app.log

[app.log](https://github.com/user-attachments/files/24370934/app.log)

### Debug enabled

- [x] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by mixio60** [comment]
<img width="2092" height="711" alt="Image" src="https://github.com/user-attachments/assets/4ec8a43b-8fff-4f14-b375-b867b8cddb9b" />

**Comment by mixio60** [comment]
<img width="783" height="250" alt="Image" src="https://github.com/user-attachments/assets/de8235d5-175b-4c1a-a571-6013eb3508a8" />

**Comment by JuicyFruiter** [comment]
FWIW I think this stopped working with a synology update as I had a similar setup that used to work that no longer works now, but I have probably made things a lot worse by trying multiple different things to resolve it without keeping a log of what i've tried, but I think Synology have somehow prevented network level access through docker.  Sorry I cant be more help

I have the same cap_adds, but in startup logs I now get:
```
⚠️  ATTENTION: Raw network capabilities are missing.

    Tools that rely on NET_RAW/NET_ADMIN/NET_BIND_SERVICE (e.g. nmap -sS,

    arp-scan, nbtscan) will not function. Restart the container with:

        --cap-add=NET_RAW --cap-add=NET_ADMIN --cap-add=NET_BIND_SERVICE

    Without those caps, NetAlertX cannot inspect your network. Fix it before

    trusting any results.

    https://github.com/jokob-sk/NetAlertX/blob/main/docs/docker-troubleshooting/missing-capabilities.md
```

**Comment by jokob-sk** [comment]
Probably related to https://github.com/jokob-sk/NetAlertX/issues/1366

**Comment by mixio60** [comment]
My interface "192.168.178.0/24 --interface=eth0" has always been the same before NetalertX v25.11.29.


<img width="2092" height="711" alt="Image" src="https://github.com/user-attachments/assets/aec3f25e-1369-4dc0-bef8-d6046f3483e6" />

**Comment by adamoutler** [comment]
See what happens when you apply this
```
    environment: 
        SKIP_STARTUP_CHECKS="excessive capabilities.sh" # skip this check during startup as it will be extra noise for you, in your case
    privileged: true  #set privileged  to true - grant everything to the container
#  Remove all drop capts/add caps/security lockdowns
#     security_opt:
#     - no-new-privileges:true
#   cap_drop:                                       # Drop all capabilities for enhanced security
#      - ALL
# keep the add caps 
    cap_add:                                        # Add only the necessary capabilities
      - NET_ADMIN                                   # Required for scanning with arp-scan, nmap, nbtscan, traceroute, and zero-conf
      - NET_RAW                                     # Required for raw socket operations with arp-scan, nmap, nbtscan, traceroute and ero-conf
      - NET_BIND_SERVICE                            # Required to bind to privileged ports with nbtscan
      - CHOWN                                       # Required for root-entrypoint to chown /data + /tmp before dropping privileges
      - SETUID                                      # Required for root-entrypoint to switch to non-root user
      - SETGID                                      # Required for root-entrypoint to switch to non-root group
```

**Comment by mixio60** [comment]
> Vedi cosa succede quando applichi questo
> 
> ```
>     environment: 
>         SKIP_STARTUP_CHECKS="excessive capabilities.sh" # skip this check during startup as it will be extra noise for you, in your case
>     privileged: true  #set privileged  to true - grant everything to the container
> #  Remove all drop capts/add caps/security lockdowns
> #     security_opt:
> #     - no-new-privileges:true
> #   cap_drop:                                       # Drop all capabilities for enhanced security
> #      - ALL
> # keep the add caps 
>     cap_add:                                        # Add only the necessary capabilities
>       - NET_ADMIN                                   # Required for scanning with arp-scan, nmap, nbtscan, traceroute, and zero-conf
>       - NET_RAW                                     # Required for raw socket operations with arp-scan, nmap, nbtscan, traceroute and ero-conf
>       - NET_BIND_SERVICE                            # Required to bind to privileged ports with nbtscan
>       - CHOWN                                       # Required for root-entrypoint to chown /data + /tmp before dropping privileges
>       - SETUID                                      # Required for root-entrypoint to switch to non-root user
>       - SETGID                                      # Required for root-entrypoint to switch to non-root group
> ```

Applied, thanks, but no improvements in progress.

**Comment by adamoutler** [comment]
I'm not understanding the issue here. My Synology runs arp scans just fine. During testing jokob-sk can run the python from command line as well as the binary just fine.  However when NetAlertX runs it, it doesn't work. I can't reproduce on my Synology 1520+ machine.

**Comment by mixio60** [comment]
> Non capisco il problema qui. Il mio Synology esegue le scansioni ARP senza problemi. Durante i test jokob-sk può eseguire Python sia dalla riga di comando che il binario senza problemi. Tuttavia, quando NetAlertX lo esegue, non funziona. Non riesco a riprodurre sulla mia macchina Synology 1520+.

Before NetAlertX v25.11.29 it always worked with an interface configured like this: 192.168.178.0/24 --interface=eth0, I have a Synology DS218+, probably with some firmware update, Synology has prevented access at the network level via docker.

<img width="1169" height="1264" alt="Image" src="https://github.com/user-attachments/assets/dee33286-7a82-4e9f-9dbd-12b6543948a9" />

**Comment by adamoutler** [comment]
> Applied, thanks, but no improvements in progress.


Please double-check the settings. 
```
services:
  netalertx:
    # ... other settings ...
    network_mode: host
    # user: "20211:20211"    # <--- Comment out the old user

    # security_opt:                      #  <--- Ensure this is definitely gone
    #  - no-new-privileges:true #  <--- Ensure this is definitely gone
```

**Comment by adamoutler** [comment]
This could be a difference in apparmor as well, if the above doesn't work, please try this and let me know what happens

 please check `dmesg | grep -i apparmor` as root on the synology command line @mixio60.  Then apply this:
```
services:
  netalertx:
    image: ghcr.io/jokob-sk/netalertx-dev:latest
    # ... other settings ...
    security_opt:
      - apparmor:unconfined
```
and check it again.  It could be more restrictive apparmor on your unit.  

I've got a 2020 DS1520+ and it seems to be working properly.

**Comment by luckylinux** [comment]
I think I also had that Error (using Podman Root inside a KVM Virtual Machine), and it was solved by either:
- Removing the `--interface=eth0` Part (just set the required Subnet)
- Removing / Disabling the Part in `compose.yml`
```
# Security Settings
    #security_opt:
    #  - no-new-privileges:true
```

**Comment by mixio60** [comment]
> > Ho fatto domanda, grazie, ma nessun miglioramento in corso.
> 
> Per favore, controlla bene le impostazioni.
> 
> ```
> services:
>   netalertx:
>     # ... other settings ...
>     network_mode: host
>     # user: "20211:20211"    # <--- Comment out the old user
> 
>     # security_opt:                      #  <--- Ensure this is definitely gone
>     #  - no-new-privileges:true #  <--- Ensure this is definitely gone
> ```

OK, Adamoutler, it's working now, that command was blocking NetAlertX in arp scanning, thanks for your tip.

**Comment by adamoutler** [comment]
This should be fixed when #1393 is merged.   You will need to set environmental variable `PUID=0`.

**Comment by jokob-sk** [comment]
Anyone in this thread who is still experiencing this issue, please try testing the `netalertx-dev` container, and set PUID/GUID in your `docker-compose.yml` file to your root user, e.g.:

```yaml
    environment:
      ...
      PUID: 0                  # Runtime UID after priming 
      PGID: 100                # Runtime GID after priming 
```

**Comment by luckylinux** [comment]
In my View that shouldn't be required.

As said before I think what did the Trick for me was:
- Removing the --interface=eth0 Part (just set the required Subnet)
- Removing / Disabling the Part in compose.yml

```
# Security Settings
    #security_opt:
    #  - no-new-privileges:true
```

Of course make sure you are running Docker / Podman ROOTFUL on either Baremetal or a full-fledged Virtual Machine (KVM, Xen, ESXi, ...). No LXC Containers (privileged could work, but I suggest NOT going there, as it's a bad Idea for several Reasons) !

Running Docker/Podman Rootless is not going to work for this use Case.

**Comment by JuicyFruiter** [comment]
updated to netalertx-dev container and added PUID/PGID.

Here is the compose:
```
services:
  netalertx:
     image: jokobsk/netalertx-dev:latest
     container_name: NetAlertX
     healthcheck:
      test: curl -f http://localhost:17811/ || exit 1
     mem_limit: 4g
     cpu_shares: 768
     network_mode: host
     # security_opt:
     # - no-new-privileges:true
     # cap_drop:
     #  - ALL                  
     cap_add:
      - NET_ADMIN                                   # Required for scanning with arp-scan, nmap, nbtscan, traceroute, and zero-conf
      - NET_RAW                                     # Required for raw socket operations with arp-scan, nmap, nbtscan, traceroute and ero-conf
      - NET_BIND_SERVICE                            # Required to bind to privileged ports with nbtscan
      - CHOWN                                       # Required for root-entrypoint to chown /data + /tmp before dropping privileges
      - SETUID                                      # Required for root-entrypoint to switch to non-root user
      - SETGID                                      # Required for root-entrypoint to switch to non-root group
     volumes:
      - /volume1/docker/netalertx/data:/data:rw
      - /etc/localtime:/etc/localtime:ro
     tmpfs:
      - "/tmp:uid=20211,gid=20211,mode=1700,rw,noexec,nosuid,nodev,async,noatime,nodiratime"
     environment:
      SKIP_STARTUP_CHECKS: "excessive capabilities.sh" # skip this check during startup as it will be extra noise for you, in your case
      PORT: 17811
      PUID: 0                  # Runtime UID after priming 
      PGID: 100                # Runtime GID after priming 
     restart: on-failure:5
```


Here are the logs:

```
WARNING: Legacy AUFS storage driver detected.

    AUFS strips file capabilities (setcap) during image extraction which breaks

    layer-2 scanners (arp-scan, etc.) when running as non-root.

    Action: set PUID=0 (root) on AUFS hosts or migrate to a supported driver.

    Details: https://github.com/jokob-sk/NetAlertX/blob/main/docs/docker-troubleshooting/aufs-capabilities.md

ℹ️  Running as root (PUID=0). Paths will be owned by root.

ℹ️  NetAlertX startup: Running privilege check and path priming as ROOT.

    (On modern systems, privileges will be dropped to PUID after setup)

⚠️  WARNING: Legacy AUFS storage driver detected.

    AUFS strips file capabilities (setcap) during image extraction which breaks

    layer-2 scanners (arp-scan, etc.) when running as non-root.

    Action: set PUID=0 (root) on AUFS hosts or migrate to a supported driver.

    Details: https://github.com/jokob-sk/NetAlertX/blob/main/docs/docker-troubleshooting/aufs-capabilities.md

ℹ️  Running as root (PUID=0). Paths will be owned by root.

 _   _      _    ___  _           _  __   __

| \ | |    | |  / _ \| |         | | \ \ / /

|  \| | ___| |_/ /_\ \ | ___ _ __| |_ \ V / 

| .   |/ _ \ __|  _  | |/ _ \  __| __|/   \ 

| |\  |  __/ |_| | | | |  __/ |  | |_/ /^\ \ 

\_| \_/\___|\__\_| |_/_|\___|_|   \__\/   \/

   Network intruder and presence detector. 

   https://netalertx.com

Startup pre-checks

--> data migration.sh 

--> capabilities audit.sh 

══════════════════════════════════════════════════════════════════════════════

🚨 ALERT: Python execution capabilities (NET_RAW/NET_ADMIN) are missing.

    The Python binary in this image has file capabilities (+eip) that

    require these bits in the container's bounding set. Without them,

    the binary will fail to execute (Operation not permitted).

    Restart with: --cap-add=NET_RAW --cap-add=NET_ADMIN

══════════════════════════════════════════════════════════════════════════════

══════════════════════════════════════════════════════════════════════════════

⚠️  WARNING: Reduced functionality (NET_BIND_SERVICE missing).

    Tools like nbtscan cannot bind to privileged ports (UDP 137).

    This will reduce discovery accuracy for legacy devices.

    Consider adding: --cap-add=NET_BIND_SERVICE

══════════════════════════════════════════════════════════════════════════════

Security context: Operational capabilities (CHOWN SETGID SETUID) not granted.

See https://github.com/jokob-sk/NetAlertX/blob/main/docs/docker-troubleshooting/missing-capabilities.md

--> mounts.py 

 Path                     | R | W | Mount | RAMDisk | Performance | DataLoss 

--------------------------+---+---+-------+---------+-------------+----------

 /data                    | ✅| ✅|   ✅  |    ➖   |      ➖     |    ✅     

 /data/db                 | ✅| ✅|   ✅  |    ➖   |      ➖     |    ✅     

 /data/config             | ✅| ✅|   ✅  |    ➖   |      ➖     |    ✅     

 /tmp/run/tmp             | ✅| ✅|   ✅  |    ✅   |      ✅     |    ✅     

 /tmp/api                 | ✅| ✅|   ✅  |    ✅   |      ✅     |    ✅     

 /tmp/log                 | ✅| ✅|   ✅  |    ✅   |      ✅     |    ✅     

 /tmp/run                 | ✅| ✅|   ✅  |    ✅   |      ✅     |    ✅     

 /tmp/nginx/active-config | ✅| ✅|   ✅  |    ✅   |      ✅     |    ✅     

--> first run config.sh 

--> first run db.sh 

--> mandatory folders.sh 

    * Creating DB locked log.

    * Creating Execution queue log.

--> apply conf override.sh 

--> writable config.sh 

--> nginx config.sh 

--> expected user id match.sh 

--> host mode network.sh 

--> excessive capabilities.sh 

\033[90mskip\033[0m

--> appliance integrity.sh 

══════════════════════════════════════════════════════════════════════════════

⚠️  Warning: Container is running as read-write, not in read-only mode.

    Please mount the root filesystem as --read-only or use read_only: true

    https://github.com/jokob-sk/NetAlertX/blob/main/docs/docker-troubleshooting/read-only-filesystem.md

══════════════════════════════════════════════════════════════════════════════

--> ports available.sh 

Starting /usr/sbin/php-fpm83 -y "/services/config/php/php-fpm.conf" -F (tee stderr to app.php_errors.log)

Starting supercronic --quiet "/services/config/cron/crontab" >>"/tmp/log/cron.log" 2>&1 &

Starting python3  -m server > /tmp/log/stdout.log 2> >(tee /tmp/log/stderr.log >&2)

Starting /usr/sbin/nginx -p "/tmp/run/" -c "/tmp/nginx/active-config/nginx.conf" -g "error_log stderr; error_log /tmp/log/nginx-error.log; daemon off;" &

2026/01/11 09:55:22 [error] 268#268: *1 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 192.168.1.28, server: , request: "GET /php/server/utilNotification.php?action=get_unread_notifications HTTP/1.1", upstream: "fastcgi://unix:/tmp/run/php.sock:", host: "192.168.1.48:17811", referrer: "http://192.168.1.48:17811/devices.php"

Successfully updated IEEE OUI database (112573 entries)

2026/01/11 09:56:22 [error] 268#268: *1 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 192.168.1.28, server: , request: "GET /php/server/utilNotification.php?action=get_unread_notifications HTTP/1.1", upstream: "fastcgi://unix:/tmp/run/php.sock:", host: "192.168.1.48:17811", referrer: "http://192.168.1.48:17811/devices.php"

2026/01/11 09:56:26 [error] 268#268: *1 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 192.168.1.28, server: , request: "GET /php/server/utilNotification.php?action=get_unread_notifications HTTP/1.1", upstream: "fastcgi://unix:/tmp/run/php.sock:", host: "192.168.1.48:17811", referrer: "http://192.168.1.48:17811/devices.php"

2026/01/11 09:56:26 [error] 268#268: *1 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 192.168.1.28, server: , request: "GET /php/server/utilNotification.php?action=get_unread_notifications HTTP/1.1", upstream: "fastcgi://unix:/tmp/run/php.sock:", host: "192.168.1.48:17811", referrer: "http://192.168.1.48:17811/devices.php"

2026/01/11 09:56:29 [error] 268#268: *1 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 192.168.1.28, server: , request: "GET /php/server/utilNotification.php?action=get_unread_notifications HTTP/1.1", upstream: "fastcgi://unix:/tmp/run/php.sock:", host: "192.168.1.48:17811", referrer: "http://192.168.1.48:17811/devices.php"
```

**Comment by jokob-sk** [comment]
Looks like it started correctly.

**Comment by jokob-sk** [comment]
Releasing -> Closing
