### ISSUE TITLE
v24.9.26 infinite loop of notification "[Upgrade] : App upgraded 🚀 Please clear the cache"

### ISSUE THREAD

**Issue by meeowgler** [jokob-sk/NetAlertX#811]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### Current Behavior

After upgrading to v24.9.26, getting an infinite loop with the notification "[Upgrade] : App upgraded 🚀 Please clear the cache" immediately appearing after clicking ok.

Followed the 4 steps in Chrome, tried in incognito and in Firefox. All create an endless loop of that notification.

### Expected Behavior

After clicking ok, clearing the browser cache, clearing the app cache, then saving settings, the notification should no longer appear.

### Steps To Reproduce

This notification appears when navigating to any netalertx page.

### app.conf

```python
#-----------------AUTOGENERATED FILE-----------------#
#                                                    #
#         Generated:  2024-09-27_21-56-13            #
#                                                    #
#   Config file for the LAN intruder detection app:  #
#      https://github.com/jokob-sk/NetAlertX         #
#                                                    #
#-----------------AUTOGENERATED FILE-----------------#


# General
#---------------------------
LOADED_PLUGINS=['ARPSCAN','CSVBCKP','DBCLNP','DHCPSRVS','INTRNT','MAINT','MQTT','NEWDEV','NMAPDEV','NTFPRCS','SETPWD','SMTP','UNFIMP','VNDRPDT','WORKFLOWS']
LOADED_PLUGINS__metadata="                      {}\n                    "
SCAN_SUBNETS=['10.1.20.0/24 --interface=eth0','10.2.0.0/24 --interface=eth0','10.2.1.0/24 --interface=eth0','10.1.30.0/24 --interface=eth0','10.1.10.0/24 --interface=eth0','10.1.0.0/24 --interface=eth0']
SCAN_SUBNETS__metadata="                      {}\n                    "
LOG_LEVEL='verbose'
LOG_LEVEL__metadata="                      {}\n                    "
TIMEZONE='America/New_York'
TIMEZONE__metadata="                      {}\n                    "
PLUGINS_KEEP_HIST=250
PLUGINS_KEEP_HIST__metadata="                      {}\n                    "
REPORT_DASHBOARD_URL='http://netalertx'
REPORT_DASHBOARD_URL__metadata="                      {}\n                    "
DAYS_TO_KEEP_EVENTS=30
DAYS_TO_KEEP_EVENTS__metadata="                      {}\n                    "
HRS_TO_KEEP_NEWDEV=0
HRS_TO_KEEP_NEWDEV__metadata="                      {}\n                    "
CLEAR_NEW_FLAG=0
CLEAR_NEW_FLAG__metadata="                      {}\n                    "
API_CUSTOM_SQL='SELECT * FROM Devices WHERE dev_PresentLastScan = 0'
API_CUSTOM_SQL__metadata="                      {}\n                    "
VERSION='1727316131'
VERSION__metadata="                      {}\n                    "
NETWORK_DEVICE_TYPES=['AP','Gateway','Firewall','Hypervisor','Powerline','Switch','WLAN','PLC','Router','USB LAN Adapter','USB WIFI Adapter','Internet']
NETWORK_DEVICE_TYPES__metadata="                      {}\n                    "

(too long)
```

### docker-compose.yml

```python
version: "3.9"
services:
  pi.alert:
     container_name: NetAlertX
     security_opt:
      - no-new-privileges:true
     volumes:
      - /mnt/nfs/docker/netalertx/config:/app/config:rw
      - /mnt/nfs/docker/netalertx/db:/app/db:rw
      - /mnt/nfs/docker/netalertx/logs:/app/front/log:rw
     environment:
      TZ: America/New_York
      PORT: 17811
     network_mode: host
     restart: unless-stopped
     image: jokobsk/netalertx:latest
```

### What branch are you running?

Production

### app.log

22:15:41 [MAIN] Setting up ...
22:15:41 [conf.tz] Setting up ...
22:15:41 

22:15:41 The backend restarted (started). If this is unexpected check https://bit.ly/NetAlertX_debug for troubleshooting tips.
22:15:41 

22:15:41 Permissions check (All should be True)
22:15:41 ------------------------------------------------
22:15:41   /config/app.conf |  READ  | True
22:15:41   /config/app.conf |  WRITE | True
22:15:41   /db/app.db       |  READ  | True
22:15:41   /db/app.db       |  WRITE | True
22:15:41 ------------------------------------------------
22:15:41 [Setup] Attempting to fix permissions.
22:15:41 [Setup] Attempting to fix permissions.
22:15:41 [Database] Opening DB
22:15:41 [upgradeDB] Re-creating Settings table
22:15:41 [upgradeDB] Re-creating Pholus_Scan table
22:15:41 [upgradeDB] Re-creating Parameters table
22:15:41 [Config] reading config file
22:15:41 [Config] Plugins: Number of all plugins (including not loaded): 36

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
Hi @meeowgler ,

Can you please enable debug and post a more detailed app.log output by following steps 1-4 from here: https://github.com/jokob-sk/NetAlertX/blob/main/docs/DEBUG_TIPS.md

Thanks,
j

**Comment by meeowgler** [comment]
[app.log](https://github.com/user-attachments/files/17174138/app.log)

**Comment by jokob-sk** [comment]
Thanks for the file. Regrettably it doesn't contain the reason for the restart. Can you please check the docker logs, for example through Portainer?

**Comment by meeowgler** [comment]
The container doesn't restart, it just stuck at this notification. Regardless of what I do, after clicking OK, the notification just pops right back. I feel like it's some sort of UI configuration issue but I can't figure it out.

![image](https://github.com/user-attachments/assets/f1468cb1-99cf-4dd0-ae7b-4b7858f788a1)

**Comment by jokob-sk** [comment]
Can you please post the error output from the container logs so that I can help further?

**Comment by meeowgler** [comment]
Of course. Thank you so much for helping with this!
[_NetAlertX_logs.txt](https://github.com/user-attachments/files/17174217/_NetAlertX_logs.txt)

Here's something else interesting. The browser dev console shows some errors:
![image](https://github.com/user-attachments/assets/09a7686c-0409-4ba1-83de-868936e29914)

**Comment by jokob-sk** [comment]
Thanks for the log. The log file doesn't include the logs just before the back end start-up where usually the error is logged. Can you please include more of the logs? A few lines before the following line should help:

 `The backend restarted (started)`

Thank you for the dev console log. I can't see anything out of the ordinary.

**Comment by meeowgler** [comment]
I fixed it!

1) I removed these two lines from app.conf:
UI_LANG='English'
UI_LANG__metadata="                      {}\n                    "
2) The UI started throwing some new errors, so I placed these two lines back.
3) Refreshed. Fixed!

So weird!

**Comment by rama31244** [comment]
I'm still having this issue despite trying to clear the cache and clicking reload. I tried clearing /app/front/api  too and this didn't help

**Comment by jokob-sk** [comment]
Locking this as the reappearing notification is a symptom only. If you experience it, please check your log. Likely the application is restarting in the background. Open a new issue so that I can help you to resolve the underlying problem.
