### ISSUE TITLE
A way to select which subnets to add to the scan (Mikrotik plugin)

### ISSUE THREAD

**Issue by stanelie** [jokob-sk/NetAlertX#836]
Hello.

My Mikrotik router is managing 8 networks, but I only care to scan for 2 of them. So, I would like to exclude them from the scan results (Mikrotik plugin). They are on distinct subnets.

Example : I would like to exclude the building's Guests network, so I don't get alerts every time someone on the sidewalk connects to it.

It would be useful to me to have a way to exclude certain subnets, or, to have a way to choose which subnets I would like to include in the scan.

Thanks!

**Comment by jokob-sk** [comment]
Hi @stanelie,

I won't be implementing plugin specific exclusions as that would overcomplicate the code and thus maintenance (e.. G. That exclusion settings would have to be configurable across all scanner plugins) 

However I think that you should be able to exclude devices with the already available settings. Please check these docs for details:
https://github.com/jokob-sk/NetAlertX/blob/main/docs/NOTIFICATIONS.md

Let me know your thoughts. 
J

**Comment by jokob-sk** [comment]
Also, please use the feature template in the future as it allows me to understand what you tried, though of and the use case. I'm not sure for example if you have considered above.

Templates help me not to get burned out of maintaining this project as they reduce the back and forth communication, so that I can focus my time better. 

Thanks in advance.

**Comment by stanelie** [comment]
Oh!
Ignored IPs from the New Devices section is the feature I was looking for.

However, after deleting all my devices and having the Mikrotik plugin re-add them, those that I excluded with the filter "10.10.%.%", as per the documentation, were still added to the list of devices (I want to not add all the 10.10.x.x devices).

Sorry about the template, I will be more careful.
Thanks!

**Comment by jokob-sk** [comment]
Nah, all good.

I think the value should then be `10.10.%`. Let me know if that works.

Thanks,
J

**Comment by stanelie** [comment]
I've tried with both 10.10.%. and 10.10.% , and I still get devices added in the 10.10.x.x range.

Thoughts?

**Comment by jokob-sk** [comment]
Hi @stanelie ,

I think I found the issue. The correct value should be `10.10.%` - without the `.` at the end.

This should be fixed in the next release. It would be great if you could test this. Can you please switch to the `netalertx-dev` docker image (backup everything at first), in about 15 minutes (or after the last [action finishes](https://github.com/jokob-sk/NetAlertX/actions)) from now. 

Thanks in advance,
j

**Comment by stanelie** [comment]
No luck. I still see the excluded subnet in the devices list.

**Comment by jokob-sk** [comment]
Hi, thanks for checking.

Just to clarify, this will stop the devices being added. However once they are in the app, they will remain seen. IF you delete one of the devices, will it reappear?

**Comment by stanelie** [comment]
Everytime I test this feature, I previously click on Delete All Devices im the maintenance tools menu.

They still reappear.

**Comment by jokob-sk** [comment]
Thanks @stanelie - I think I overlooked one query - weird that no one complained about this before. 


Hopefully now this truly works now. 

It would be great if you could test this. Can you please switch to the netalertx-dev docker image (backup everything at first), in about 15 minutes (or after the last [action finishes](https://github.com/jokob-sk/NetAlertX/actions)) from now.

Thanks in advance,
j

**Comment by stanelie** [comment]
It works!
🎉

**Comment by jokob-sk** [comment]
Yayyyy 🍾 🙂

**Comment by jokob-sk** [comment]
I will close this as released and solved
