### ISSUE TITLE
[Bug] Archived devices visible in my device dashboard

### ISSUE THREAD

**Issue by dtech77pl** [jokob-sk/NetAlertX#920]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### The issue occurs in the following browsers. Select at least 2.

- [ ] Firefox
- [X] Chrome
- [X] Edge
- [ ] Safari (unsupported) - PRs welcome
- [ ] N/A - This is an issue with the backend

### Current Behavior

Disabled Archived devices to be visible in my devices and still are there. 

### Expected Behavior

Cache was deleted, I have try on the new installed PC stil the same. 
Remove archived devices from my-device list. 

### What branch are you running?

Production

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
Hi @dtech77pl ,

Have you tried removing the `archived` from the `UI_MY_DEVICES` setting?

![image](https://github.com/user-attachments/assets/55de8384-f7d1-40af-b7d5-2f60a89b8c01)

**Comment by dtech77pl** [comment]
This is how it's setup.
[http://techmanski.pl/pub/ws2.jpg](url)

**Comment by jokob-sk** [comment]
Thanks for the details. 

I was able to reproduce the issue and the fix should be available in the next release. 

If a device is DOWN and marked as ARCHIVED it will be now hidden from My Devices.

It would be great if you could test this. Can you please switch to the `netalertx-dev` docker image (backup everything at first or, ideally spin up a **separate container with a separate db and config**), in about 15 minutes (or after the last [action finishes](https://github.com/jokob-sk/NetAlertX/actions)) from now?

Make sure you refresh your browser cache - and click the 🔄 refresh button in the top right corner.

Thanks in advance,
j

**Comment by dtech77pl** [comment]
Dev got some issue and cannot be started, got this error message:

[http://techmanski.pl/pub/dev1.jpg](url)

**Comment by jokob-sk** [comment]
Hi @dtech77pl ,

I just pushed hopefully a fix. Can you try re-downloading the dev image in ~15 min form now and follow the below steps?

Can you try restarting the application (Maintenance -> Log -> Restart Server or Restart the Container ) and clearing the cache (app AND browser cache) if that helps?

Try saving the configuration afterward. 

Let me know if that helps - thanks in advance,
j

**Comment by dtech77pl** [comment]
I have pulled brand new instalnce of the dev and still have the same error: 

DataTables warning: table id=tableDevices - Unauthorized

This is my docker settings:

version: "3"
services:
  netalertx:
    container_name: netalertx-dev-Warsaw
    hostname: netalertx-dev-Warsaw
#    ui_dark_mode: true  
#    ui_theme: dark
    privileged: true
    # use the below line if you want to test the latest dev image
    # image: "jokobsk/netalertx-dev:latest" 
    image: jokobsk/netalertx-dev:latest
    environment:
      - TZ=Europe/Warsaw
      - PORT=20222
    restart: always
    volumes:
      - /volume1/docker/netalertx-dev/config:/app/config
      - /volume1/docker/netalertx-dev/db:/app/db      
      # (optional) useful for debugging if you have issues setting up the container
      - /volume1/docker/netalertx-dev/logs:/app/front/log
#      - type: tmpfs
#        target: /app/api
    network_mode: host

**Comment by jokob-sk** [comment]
Hi @dtech77pl ,

Thanks for the details. 

Looks like one of the NAX instances is trying to access another's GraphQL server.

Can you please make sure you have unique `GRAPHQL_PORT` settings across your NAX instances running on the same `host`?

 You can initialize the setting via the ENV variable `APP_CONF_OVERRIDE`, like this:

```yaml
services:
  netalertx_fresh:
    container_name: netalertx_fresh
    image: "jokobsk/netalertx-dev"
    network_mode: "host"
    volumes:
      - ${APP_DATA_LOCATION}/netalertx_fresh/config:/app/config
      - ${APP_DATA_LOCATION}/netalertx_fresh/db:/app/db
    environment:
      - TZ=Australia/Sydney
      - HOST_USER_ID=1036
      - HOST_USER_GID=1000
      - PORT=22222
      - ALWAYS_FRESH_INSTALL=true
      - APP_CONF_OVERRIDE={"GRAPHQL_PORT":"20223","UI_theme":"Light"}
```

**Comment by dtech77pl** [comment]
This build fixes this. Once I have disabled archived devices from being visible in the settings, I do not see it. Thank you for this. 
Can you also check the total of my device number to be counted without archived ?

**Comment by jokob-sk** [comment]
Hi @dtech77pl ,

Glad to hear it's working and thanks for testing it!

If you refer to the the "My Devices" count then it should update after a refresh or two. I think the value is cached.

**Comment by dtech77pl** [comment]
You are right, number is now equal to all live devices without archived one. 
Looking forward for the new stable release.

Thank you for your support

**Comment by jokob-sk** [comment]
Thanks for the confirmation!

**Comment by jokob-sk** [comment]
Closing -> Releasing
