### ISSUE TITLE
Problems with the update modal

### ISSUE THREAD

**Issue by RmG152** [jokob-sk/NetAlertX#992]
### Is there an existing issue for this?

- [x] I have searched the existing open and closed issues and I checked the docs https://jokob-sk.github.io/NetAlertX/

### The issue occurs in the following browsers. Select at least 2.

- [x] Firefox
- [ ] Chrome
- [ ] Edge
- [ ] Safari (unsupported) - PRs welcome
- [ ] N/A - This is an issue with the backend

### Current Behavior

The Update Notification modal window does not allow you to perform the steps and keeps opening in a loop.

After refreshing tab using shift + refresh button, the window keeps continues to open several times:

![Image](https://github.com/user-attachments/assets/ead7ebf8-9738-40e3-8ba7-f395144e5b19)

When you click ok, the modal closes, but leaves a backdrop that blocks interaction with the application, preventing you from using the application's cache clearing options or saving your settings:

![Image](https://github.com/user-attachments/assets/db407f0c-5bee-4a76-9d2c-e63297257192)

![Image](https://github.com/user-attachments/assets/0261108f-8401-4206-9d74-bbd815e93d38)

### Expected Behavior

The modal should not loop immediately, there should be a delay to allow the user to interact with the page.

When the modal closes, the backdrop should be removed to allow interaction with the page.

Temporary solution:
Access the developer tools and delete all data in storage multiple times and repeat the steps manually by deleting the backdrop from the inspector.

### Steps To Reproduce

1. Upgrade using the docker image
2. Open the web interface in Firefox

### app.conf

```python

```

### docker-compose.yml

```python

```

### What installation are you running?

Production (netalertx)

### Debug enabled

- [x] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
Thanks for the report. 

I couldn't reproduce the issue, but I implemented a check to only display a modal if none is already displayed which should prevent this from happening. 

It would be great if you could test this. Can you please switch to the `netalertx-dev` docker image (backup everything at first or, ideally spin up a **separate container with a separate db and config**), in about 15 minutes (or after the last [action finishes](https://github.com/jokob-sk/NetAlertX/actions)) from now?

Thanks in advance,
j

**Comment by RmG152** [comment]
I have done a clean installation, in this installation the modal is not shown in loop.


The steps still do not work, the configuration does not load (clean installation).

### app.conf

```python
#-----------------AUTOGENERATED FILE-----------------#
#                                                    #
#         Generated:  2022-12-30_22-19-40            #
#                                                    #
#   Config file for the LAN intruder detection app:  #
#      https://github.com/jokob-sk/NetAlertX         #
#                                                    #
#-----------------AUTOGENERATED FILE-----------------#

# 🔺 Use the Settings UI - only edit when necessary 🔺

# General
#---------------------------
# Scan using interface eth0
# SCAN_SUBNETS    = ['192.168.1.0/24 --interface=eth0']
#
# Scan multiple interfaces (eth1 and eth0):
# SCAN_SUBNETS    = [ '192.168.1.0/24 --interface=eth1', '192.168.1.0/24 --interface=eth0' ]

DISCOVER_PLUGINS=True
SCAN_SUBNETS=['192.168.1.0/24 --interface=eth0']
TIMEZONE='Europe/Madrid'
LOADED_PLUGINS = ['ARPSCAN','CSVBCKP','DBCLNP', 'INTRNT','MAINT','NEWDEV','NSLOOKUP','NTFPRCS', 'AVAHISCAN', 'SETPWD','SMTP', 'SYNC', 'VNDRPDT', 'WORKFLOWS', 'UI']

DAYS_TO_KEEP_EVENTS=90
# Used for generating links in emails. Make sure not to add a trailing slash!
REPORT_DASHBOARD_URL='http://netalertx'

# Make sure at least these scanners are enabled for new installs, other defaults are taken from the config.json
INTRNT_RUN='schedule'
ARPSCAN_RUN='schedule'
NSLOOKUP_RUN='before_name_updates'

# Email 
#-------------------------------------
# (add SMTP to LOADED_PLUGINS to load)
#-------------------------------------
SMTP_RUN='disabled'  # use 'on_notification' to enable
SMTP_SERVER='smtp.gmail.com'
SMTP_PORT=587
SMTP_REPORT_TO='user@gmail.com'
SMTP_REPORT_FROM='NetAlertX <user@gmail.com>'
SMTP_SKIP_LOGIN=False
SMTP_USER='user@gmail.com'
SMTP_PASS='password'
SMTP_SKIP_TLS=False


# Webhook 
#-------------------------------------
# (add WEBHOOK to LOADED_PLUGINS to load)
#-------------------------------------
WEBHOOK_RUN='disabled'  # use 'on_notification' to enable
WEBHOOK_URL='http://n8n.local:5555/webhook-test/aaaaaaaa-aaaa-aaaa-aaaaa-aaaaaaaaaaaa'
WEBHOOK_PAYLOAD='json'                 # webhook payload data format for the "body > attachements > text" attribute 
                                       # in https://github.com/jokob-sk/NetAlertX/blob/main/docs/webhook_json_sample.json 
                                       #   supported values: 'json', 'html' or 'text'
                                       #   e.g.: for discord use 'html'
WEBHOOK_REQUEST_METHOD='GET'


# Apprise 
#-------------------------------------
# (add APPRISE to LOADED_PLUGINS to load)
#-------------------------------------
APPRISE_RUN='disabled'  # use 'on_notification' to enable
APPRISE_HOST='http://localhost:8000/notify'
APPRISE_URL='mailto://smtp-relay.sendinblue.com:587?from=user@gmail.com&name=apprise&user=user@gmail.com&pass=password&to=user@gmail.com'


# NTFY
#------------------------------------- 
# (add NTFY to LOADED_PLUGINS to load)
#-------------------------------------
NTFY_RUN='disabled'  # use 'on_notification' to enable
NTFY_HOST='https://ntfy.sh'
NTFY_TOPIC='replace_my_secure_topicname_91h889f28'
NTFY_USER='user'
NTFY_PASSWORD='passw0rd'


# PUSHSAFER 
#-------------------------------------
# (add PUSHSAFER to LOADED_PLUGINS to load)
#-------------------------------------
PUSHSAFER_RUN='disabled'  # use 'on_notification' to enable
PUSHSAFER_TOKEN='ApiKey'


# MQTT 
#-------------------------------------
# (add MQTT to LOADED_PLUGINS to load)
#-------------------------------------
MQTT_RUN='disabled'  # use 'on_notification' to enable
MQTT_BROKER='192.168.1.2'
MQTT_PORT=1883
MQTT_USER='mqtt'
MQTT_PASSWORD='passw0rd'
MQTT_QOS=0
MQTT_DELAY_SEC=2


#-------------------IMPORTANT INFO-------------------#
#   This file is ingested by a python script, so if  #
#        modified it needs to use python syntax      #
#-------------------IMPORTANT INFO-------------------#

```

### docker-compose.yml

```python
version: "3"
services:
  netalertx:
    container_name: NetAlertX-dev
    hostname: NetAlertX-dev
    # use the below line if you want to test the latest dev image
    # image: "jokobsk/netalertx-dev:latest" 
    image: "jokobsk/netalertx-dev:latest"      
    network_mode: "host"   
    privileged: true
    restart: unless-stopped
    volumes:
      - ./netalertx-dev/config:/app/config
      - ./netalertx-dev/db:/app/db      
      # (optional) useful for debugging if you have issues setting up the container
      - ./netalertx-dev/logs:/app/front/log
    environment:
      - TZ=Europe/Madrid      
      - PORT=20212
```

**Comment by jokob-sk** [comment]
Hi @RmG152 ,

Just tried a fresh install and it works without issues on my end. Could you please try a simplified docker-compose file to rule out any permission issues?

Here's an example 

```yaml

services:
  netalertx_fresh:
    container_name: netalertx_fresh
    image: "jokobsk/netalertx-dev"
    network_mode: "host"
    environment:
      - TZ=Europe/Berlin
      - PORT=20212
```

**Comment by RmG152** [comment]
Sorry, I've been busy for a few weeks.

Upgrading from the March version to the April version no longer reproduces the problem, it updates correctly and does not show multiple popups.
